node {
     docker.image('maven:3-alpine').inside('-v /root/.m2:/root/.m2') {
 	stage('Build') {
                sh 'mvn -B -DskipTests clean package'
		sh 'mvn clean install -Denforcer.fail=false'
		echo "Some code compilation here..."
        }
        stage('Test') {
                sh 'mvn test'
               junit 'target/surefire-reports/*.xml'
	       echo "Some code compilation here..."
        }
        stage('Deliver') {
                sh './jenkins/scripts/deliver.sh'
		echo "Some code compilation here..."
        }
    }

}

