node {
     docker.image('maven:3.8.1-adoptopenjdk-11').inside('-v /root/.m2:/root/.m2') {
 	stage('Build') {
                sh 'mvn - f .../simple-java-maven/pom.xml clean test'
                sh 'mvn -B -DskipTests clean package'
        }
        stage('Test') {
                sh 'mvn test'
               junit 'target/surefire-reports/*.xml'
        }
        
    }

}